from numpy import np

In [2]:
import numpy as np
v1= np.array([1,2,3])
v2=np.array([4,5,6])

print("Vector v1:", v1)
print("Vector v2:", v2)

Vector v1: [1 2 3]
Vector v2: [4 5 6]


In [5]:
#vector addition
v3=v2+v1
print("Addition of both vectors is :",v3)

Addition of both vectors is : [5 7 9]


In [6]:
#vector dot product
dot_product= np.dot(v1, v2)
print("Dot product(v1,v2):", dot_product)

Dot product(v1,v2): 32


In [8]:
#vecotr norm (magnitude):
norm_v1=np.linalg.norm(v1)
print("Norm (magnitude) pof v1:", norm_v1)

Norm (magnitude) pof v1: 3.7416573867739413


2. Matrices and basic operations:

In [12]:
A= np.array([[1, 2], [3, 4]])
B= np.array([[5, 6], [7, 8]])

print("Mterix a:",A)
print("Materix 2:",B)

Mterix a: [[1 2]
 [3 4]]
Materix 2: [[5 6]
 [7 8]]


In [16]:
#matrix addition
matrix_add= A+B
print("added matrices: A+B:\n", matrix_add)

added matrices: A+B:
 [[ 6  8]
 [10 12]]


In [18]:
#matrix multiplication (element-wise and dot product):
elementwise_mult= A*B  
dot_product_mult= np.dot(A, B)

print("matrix A:\n",A)
print("matrix B:\n",B)
print("element-wise multiplication:\n", elementwise_mult)
print("dot product:\n", dot_product_mult)


matrix A:
 [[1 2]
 [3 4]]
matrix B:
 [[5 6]
 [7 8]]
element-wise multiplication:
 [[ 5 12]
 [21 32]]
dot product:
 [[19 22]
 [43 50]]


In [25]:
# Matrix multiplaictions function execution between two matrices:
def matrix_multiplication(matrix1, matrix2):

    #get the number of rows and columns for both matrices
    rows_matrix1= len(matrix1)
    cols_matrix1= len(matrix1[0])
    rows_matrix2= len(matrix2)
    cols_matrix2= len(matrix2[0])

    #check if the number of columns in the first matrix is equal to the number of rows in the second matrix
    if cols_matrix1 != rows_matrix2:
        raise ValueError("Number of columns in Matrix1 must be equal to the number of rows in Matrix2 for multiplication.")   

     #initialize the result matrix with zeros to store values
    result= [[0 for _ in range(cols_matrix2)] for _ in range(rows_matrix1)] 

     #Perofrm matrix multiplication using nested loops:
    for i in range (rows_matrix1):
        for j in range (cols_matrix2):
            for k in range(cols_matrix1):
                result [i][j] += matrix1[i][k] * matrix2[k][j]

    return result  #returns the resilt here

#Example usage:
matrix1= [[1, 2, 3], [4, 5, 6]]
matrix2= [[7, 8], [9, 10], [11, 12]]

result= matrix_multiplication(matrix1, matrix2)

#print the resulting matrix:
print("Result of matrix multiplication:")
#print(result)
for row in result:
    print(row)

Result of matrix multiplication:
[58, 64]
[139, 154]


In [26]:
L = np.random.rand(3, 2)
M = np.random.rand(2, 4)
P = np.dot(L, M)
print("Matrix L:\n", L)
print("Matrix M:\n", M)
print("Matrix P:\n", P)

Matrix L:
 [[0.09802227 0.21678055]
 [0.72283428 0.29972901]
 [0.45183963 0.57680103]]
Matrix M:
 [[0.48248635 0.65041817 0.05738819 0.45057888]
 [0.87920627 0.42908813 0.36470372 0.43347792]]
Matrix P:
 [[0.23788923 0.15677343 0.08468599 0.13813635]
 [0.6122813  0.59875471 0.15079444 0.45561977]
 [0.72513354 0.54138318 0.23629174 0.45361991]]


3. Matrix Transpose

In [27]:
transpose_A = A.T
print("Matrix A:\n", A)
print("Transpose of A:\n", transpose_A)

Matrix A:
 [[1 2]
 [3 4]]
Transpose of A:
 [[1 3]
 [2 4]]


4. Determinant of matrix:

In [28]:
det_A = np.linalg.det(A)
print("Determinant of A:", det_A)

Determinant of A: -2.0000000000000004


In [35]:
def get_minor(matrix, row, col):
    # helper function to get the minor of the matrix after removing the specified row and column
    minor = [row[:col] + row[col+1:]
    for row in (matrix[:row] + matrix[row+1:])]
    return minor
 
def determinant(matrix):
    #base case for 2x2 matrix
    if len(matrix) == 2:
        return matrix[0][0] * matrix[1][1] - matrix[0][1] * matrix[1][0]

    det = 0.0
    for col in range(len(matrix)):
        cofactor = (-1) ** col #alternating sign for cofactor expansion
        minor= get_minor(matrix, 0, col)
        det += cofactor * matrix[0][col] * determinant(minor)


    return det 

#Example usage:
matrix_2x2=[[1, 2], [3, 4]]
matrix_3x3=[[6, 1 ,1], [4, -2, 5], [2, 8, 7]]
m = get_minor(matrix_3x3, 0, 0)
print(m)
print(matrix_3x3)
print("Determinant of 2x2 matrix:", determinant(matrix_2x2))
print("Determinant of 3x3 matrix:", determinant(matrix_3x3))

[[-2, 5], [8, 7]]
[[6, 1, 1], [4, -2, 5], [2, 8, 7]]
Determinant of 2x2 matrix: -2
Determinant of 3x3 matrix: -306.0


5. Inverse of a matrix

In [36]:
try:
    inv_a = np.linalg.inv(A)
    print("Inverse of A:\n", inv_a)
except np.linalg.LinAlgError:
    '''Singular matrix isa matrix with det() = 0'''
    print("Matrix A is singular and cannot be inverted.")

Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]


EIGENVALUES ABD EIGENVECTORS :-

In [39]:
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues of A:", eigenvalues)
print("Eigenvectors of A:\n", eigenvectors)

Eigenvalues of A: [-0.37228132  5.37228132]
Eigenvectors of A:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [43]:
b= np.array([5,7])

#solve the system: Ax=b
solution = np.linalg.solve(A, b)
print("Matrix A:\n", A)

print("Vector b:\n", b)
print(f" Solution of the system Ax=b where b={b} is:\n", solution)

Matrix A:
 [[1 2]
 [3 4]]
Vector b:
 [5 7]
 Solution of the system Ax=b where b=[5 7] is:
 [-3.  4.]


Solving a system of linear equation's

In [44]:
U, S, Vt = np.linalg.svd(A)
print("Matrix U:\n", U)
print("Singular Values:\n", S)
print("Matrix V transpose:\n", Vt)

Matrix U:
 [[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]
Singular Values:
 [5.4649857  0.36596619]
Matrix V transpose:
 [[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]
